=== ksilin/pyschemer/tests/price_schema_v1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "PriceData",
    "type": "object",
    "properties": {
      "mkey": {
        "type": "string"
      },
      "MATNR": {
        "type": "string"
      },
      "MTART": {
        "type": "string"
      },
      "MLFB_PRINT": {
        "type": "string"
      },
      "MLFB_SORT": {
        "type": "string"
      },
      "SHORT_OPTIONS": {
        "type": "string"
      },
      "TECH_PRDGR": {
        "type": "string"
      },
      "SENDE_ORGID": {
        "type": "string"
      },
      "PRODV": {
        "type": "string"
      },
      "MVKE_VKORG": {
        "type": "string"
      },
      "MVKE_VMSTA": {
        "type": "string"
      },
      "MVKE_VMSTD": {
        "type": "string"
      },
      "MVKE_VGBK": {
        "type": "string"
      },
      "MVKE_EGHID": {
        "type": "string"
      },
      "MVKE_VFGRP": {
        "type": "string"
      },
      "MVKE_PRGRP_GG": {
        "type": "string"
      },
      "MVKE_BSPER": {
        "type": "string"
      },
      "MVKE_TIEFG": {
        "type": "string"
      },
      "MVKE_BWARN": {
        "type": "string"
      },
      "MVKE_PRAUSG": {
        "type": "string"
      },
      "MVKE_DIV02L": {
        "type": "string"
      },
      "KBETR_ZLP0_HQ": {
        "type": "string"
      },
      "KBETR_ZLP0_RG": {
        "type": "string"
      },
      "LIFZ_N001": {
        "type": "string"
      },
      "LIFZ_N002": {
        "type": "string"
      },
      "LIFZ_N003": {
        "type": "string"
      },
      "MEAN_HE": {
        "type": "string"
      },
      "MEAN_UC": {
        "type": "string"
      }
    },
    "required": [
      "mkey",
      "MATNR",
      "MLFB_PRINT",
      "MLFB_SORT",
      "MVKE_VKORG",
      "MVKE_VMSTA"
    ]
  }

=== ksilin/pyschemer/tests/price_data_v1.json
{
    "mkey": "ABCDEFGHI",
    "MATNR": "ABCDEFGH",
    "MLFB_PRINT": "ABCDEFG",
    "MLFB_SORT": "ABCDEFGHIJK",
    "MVKE_VKORG": "ABCDEFGHIJKLMNOPQRSTUVWX",
    "MVKE_VMSTA": "ABCDEFGHIJKLMNOPQRSTUV",
    "MTART": "ABCDEFGHIJKLMNO",
    "SHORT_OPTIONS": "ABCDEFGHIJKLM",
    "TECH_PRDGR": "ABCDEFGHIJKLMNOPQRSTU",
    "SENDE_ORGID": "ABCDEFGHIJKL",
    "PRODV": "ABCDEFGHIJK",
    "MVKE_VMSTD": "ABCDEFGHIJKLMNO",
    "MVKE_VGBK": "ABCDEFGHIJKLMNOPQR",
    "MVKE_EGHID": "ABCDEFGHIJKLMNOPQRSTUVWX",
    "MVKE_VFGRP": "ABCDEFGHIJKLMNOPQRST",
    "MVKE_PRGRP_GG": "ABCDE",
    "MVKE_BSPER": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "MVKE_TIEFG": "ABCDEFGHIJKLMNOPQ",
    "MVKE_BWARN": "ABCDEFG",
    "MVKE_PRAUSG": "ABCDEFGHIJKLMNOPQRS",
    "MVKE_DIV02L": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "KBETR_ZLP0_HQ": "ABCDEFGHIJKLMNOPQRSTUVWX",
    "KBETR_ZLP0_RG": "ABCDEFGHIJKLMN",
    "LIFZ_N001": "ABCDEFGHIJKLMNOPQRSTUVWXYZABC",
    "LIFZ_N002": "ABCDEFGHIJKLMNOPQRSTUVWXY",
    "LIFZ_N003": "ABCDEFGHIJKLMNOPQR",
    "MEAN_HE": "ABCDEFGHIJKLMNOPQRSTUVWXYZAB",
    "MEAN_UC": "ABCDEFGHIJKLMNOPQRSTU"
  }
