=== ksilin/pyschemer/tests/si_prod_schema_v1.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Product",
    "type": "object",
    "properties": {
      "MATNR": {
        "type": "string"
      },
      "ZDXG_YYBCEZNDR": {
        "type": "string"
      },
      "ZDXG_YYBCEZNSO": {
        "type": "string"
      },
      "ZDXG_YYKURZANGA": {
        "type": "string"
      },
      "VKORG": {
        "type": "string"
      },
      "CH_CLUST_KOND": {
        "type": "object",
        "properties": {
          "ZLP0_1000": {
            "type": "object",
            "properties": {
              "KSCHL": {
                "type": "string"
              },
              "KOTABNR": {
                "type": "string"
              },
              "VTWEG": {
                "type": "string"
              },
              "#############": {
                "type": "string"
              },
              "DATBI": {
                "type": "string"
              },
              "DATAB": {
                "type": "string"
              },
              "KSTBM": {
                "type": "string"
              },
              "KBETR": {
                "type": "string"
              },
              "KONWA": {
                "type": "string"
              },
              "KPEIN": {
                "type": "string"
              },
              "KMEIN": {
                "type": "string"
              },
              "ZDXG_DATA_ORIGIN": {
                "type": "string"
              }
            },
            "required": [
              "KSCHL",
              "KOTABNR",
              "VTWEG",
              "#############",
              "DATBI",
              "DATAB",
              "KSTBM",
              "KBETR",
              "KONWA",
              "KPEIN",
              "KMEIN",
              "ZDXG_DATA_ORIGIN"
            ]
          },
          "ZLP0_RG": {
            "type": "object",
            "properties": {
              "KSCHL": {
                "type": "string"
              },
              "KOTABNR": {
                "type": "string"
              },
              "VTWEG": {
                "type": "string"
              },
              "#############": {
                "type": "string"
              },
              "DATBI": {
                "type": "string"
              },
              "DATAB": {
                "type": "string"
              },
              "KSTBM": {
                "type": "string"
              },
              "KBETR": {
                "type": "string"
              },
              "KONWA": {
                "type": "string"
              },
              "KPEIN": {
                "type": "string"
              },
              "KMEIN": {
                "type": "string"
              },
              "ZDXG_DATA_ORIGIN": {
                "type": "string"
              }
            },
            "required": [
              "KSCHL",
              "KOTABNR",
              "VTWEG",
              "#############",
              "DATBI",
              "DATAB",
              "KSTBM",
              "KBETR",
              "KONWA",
              "KPEIN",
              "KMEIN",
              "ZDXG_DATA_ORIGIN"
            ]
          }
        },
        "required": [
          "ZLP0_1000",
          "ZLP0_RG"
        ]
      },
      "CH_CLUST_MARD": {
        "type": "object",
        "properties": {
          "N001": {
            "type": "object",
            "properties": {
              "WERKS": {
                "type": "string"
              },
              "ZDXG_LIFNR": {
                "type": "string"
              },
              "ZDXG_LIFZ": {
                "type": "string"
              },
              "ZDXG_MINBM": {
                "type": "string"
              },
              "ZDXG_NORBM": {
                "type": "string"
              },
              "ZDXG_MAXBM": {
                "type": "string"
              },
              "ZDXG_STFBM": {
                "type": "string"
              },
              "ZDXG_VPART": {
                "type": "string"
              },
              "ZDXG_VPMNO": {
                "type": "string"
              },
              "ZDXG_VPMGR": {
                "type": "string"
              },
              "ZDXG_VPMEH": {
                "type": "string"
              },
              "ZDXG_DATA_ORIGIN": {
                "type": "string"
              },
              "LAND1": {
                "type": "string"
              },
              "ZDXG_VLIEF": {
                "type": "string"
              },
              "ZDXG_GENFLAG": {
                "type": "string"
              }
            },
            "required": [
              "WERKS",
              "ZDXG_LIFNR",
              "ZDXG_LIFZ",
              "ZDXG_MINBM",
              "ZDXG_NORBM",
              "ZDXG_MAXBM",
              "ZDXG_STFBM",
              "ZDXG_VPART",
              "ZDXG_VPMNO",
              "ZDXG_VPMGR",
              "ZDXG_VPMEH",
              "ZDXG_DATA_ORIGIN",
              "LAND1",
              "ZDXG_VLIEF",
              "ZDXG_GENFLAG"
            ]
          },
          "N002": {
            "type": "object",
            "properties": {
              "WERKS": {
                "type": "string"
              },
              "ZDXG_LIFNR": {
                "type": "string"
              },
              "ZDXG_LIFZ": {
                "type": "string"
              },
              "ZDXG_MINBM": {
                "type": "string"
              },
              "ZDXG_NORBM": {
                "type": "string"
              },
              "ZDXG_MAXBM": {
                "type": "string"
              },
              "ZDXG_STFBM": {
                "type": "string"
              },
              "ZDXG_VPART": {
                "type": "string"
              },
              "ZDXG_VPMNO": {
                "type": "string"
              },
              "ZDXG_VPMGR": {
                "type": "string"
              },
              "ZDXG_VPMEH": {
                "type": "string"
              },
              "ZDXG_LIFZ_AA": {
                "type": "string"
              },
              "ZDXG_DATA_ORIGIN": {
                "type": "string"
              },
              "LAND1": {
                "type": "string"
              },
              "ZDXG_GENFLAG": {
                "type": "string"
              }
            },
            "required": [
              "WERKS",
              "ZDXG_LIFNR",
              "ZDXG_LIFZ",
              "ZDXG_MINBM",
              "ZDXG_NORBM",
              "ZDXG_MAXBM",
              "ZDXG_STFBM",
              "ZDXG_VPART",
              "ZDXG_VPMNO",
              "ZDXG_VPMGR",
              "ZDXG_VPMEH",
              "ZDXG_LIFZ_AA",
              "ZDXG_DATA_ORIGIN",
              "LAND1",
              "ZDXG_GENFLAG"
            ]
          }
        },
        "required": [
          "N001",
          "N002"
        ]
      },
      "CH_CLUST_MEAN": {
        "type": "object",
        "properties": {
          "HE": {
            "type": "object",
            "properties": {
              "EAN11": {
                "type": "string"
              },
              "EANTP": {
                "type": "string"
              },
              "HPEAN": {
                "type": "string"
              }
            },
            "required": [
              "EAN11",
              "EANTP",
              "HPEAN"
            ]
          },
          "UC": {
            "type": "object",
            "properties": {
              "EAN11": {
                "type": "string"
              },
              "EANTP": {
                "type": "string"
              }
            },
            "required": [
              "EAN11",
              "EANTP"
            ]
          }
        },
        "required": [
          "HE",
          "UC"
        ]
      },
      "CH_CLUST_MARA": {
        "type": "object",
        "properties": {
          "MTART": {
            "type": "string"
          },
          "MBRSH": {
            "type": "string"
          },
          "MATKL": {
            "type": "string"
          },
          "MEINS": {
            "type": "string"
          },
          "BRGEW": {
            "type": "string"
          },
          "NTGEW": {
            "type": "string"
          },
          "GEWEI": {
            "type": "string"
          },
          "SPART": {
            "type": "string"
          },
          "EXTWG": {
            "type": "string"
          },
          "ZDXG_SORT_02": {
            "type": "string"
          },
          "ZDXG_SORT_04": {
            "type": "string"
          },
          "ZDXG_FDBGT": {
            "type": "string"
          },
          "ZDXG_ABGEB": {
            "type": "string"
          },
          "ZDXG_VERANTW": {
            "type": "string"
          },
          "ZDXG_VERTRIEB": {
            "type": "string"
          },
          "ZDXG_YYLASTUPD": {
            "type": "string"
          },
          "ZDXG_YYMASCH": {
            "type": "string"
          },
          "ZDXG_DATA_ORIGIN": {
            "type": "string"
          },
          "ZDXG_0007": {
            "type": "string"
          },
          "ZDXG_YYBCNORM": {
            "type": "string"
          },
          "ZDXG_SWPFV": {
            "type": "string"
          },
          "ERSDA": {
            "type": "string"
          },
          "LAEDA": {
            "type": "string"
          },
          "ZDXS_MARA_EXT1": {
            "type": "object",
            "properties": {
              "ZDXG_PRODIS": {
                "type": "string"
              },
              "ZDXG_TECH_PRDGR": {
                "type": "string"
              },
              "ZDXG_MHAFR": {
                "type": "string"
              },
              "LAENGE": {
                "type": "string"
              },
              "BREITE": {
                "type": "string"
              },
              "HOEHE": {
                "type": "string"
              },
              "ZDXG_SENDE_ORGID": {
                "type": "string"
              },
              "ZDXG_PRODV": {
                "type": "string"
              },
              "ZDXG_FUEHRSPR": {
                "type": "string"
              },
              "ZDXG_FUEHRSPR_LAISO": {
                "type": "string"
              },
              "ZDXG_GG_FLAG": {
                "type": "string"
              },
              "ZDXG_GG_HINW": {
                "type": "string"
              }
            },
            "required": [
              "ZDXG_PRODIS",
              "ZDXG_TECH_PRDGR",
              "ZDXG_MHAFR",
              "LAENGE",
              "BREITE",
              "HOEHE",
              "ZDXG_SENDE_ORGID",
              "ZDXG_PRODV",
              "ZDXG_FUEHRSPR",
              "ZDXG_FUEHRSPR_LAISO",
              "ZDXG_GG_FLAG",
              "ZDXG_GG_HINW"
            ]
          }
        },
        "required": [
          "MTART",
          "MBRSH",
          "MATKL",
          "MEINS",
          "BRGEW",
          "NTGEW",
          "GEWEI",
          "SPART",
          "EXTWG",
          "ZDXG_SORT_02",
          "ZDXG_SORT_04",
          "ZDXG_FDBGT",
          "ZDXG_ABGEB",
          "ZDXG_VERANTW",
          "ZDXG_VERTRIEB",
          "ZDXG_YYLASTUPD",
          "ZDXG_YYMASCH",
          "ZDXG_DATA_ORIGIN",
          "ZDXG_0007",
          "ZDXG_YYBCNORM",
          "ZDXG_SWPFV",
          "ERSDA",
          "LAEDA",
          "ZDXS_MARA_EXT1"
        ]
      },
      "CH_CLUST_MVKE": {
        "type": "object",
        "properties": {
          "VTWEG": {
            "type": "string"
          },
          "SKTOF": {
            "type": "string"
          },
          "VMSTA": {
            "type": "string"
          },
          "VMSTD": {
            "type": "string"
          },
          "ZDXG_VGBK": {
            "type": "string"
          },
          "ZDXG_VFGRP": {
            "type": "string"
          },
          "ZDXG_LKZ01": {
            "type": "string"
          },
          "ZDXG_LKZ19": {
            "type": "string"
          },
          "ZDXG_PRKLA": {
            "type": "string"
          },
          "ZDXG_EGHID": {
            "type": "string"
          },
          "ZDXG_PRGRP_GG": {
            "type": "string"
          },
          "ZDXG_MALL": {
            "type": "string"
          },
          "ZDXG_RGGEW": {
            "type": "string"
          },
          "ZDXG_M50FI": {
            "type": "string"
          },
          "ZDXG_M55PA": {
            "type": "string"
          },
          "ZDXG_M65VF": {
            "type": "string"
          },
          "ZDXG_M80LF": {
            "type": "string"
          },
          "ZDXG_M90AE": {
            "type": "string"
          },
          "ZDXG_M91TS": {
            "type": "string"
          },
          "ZDXG_M99MH": {
            "type": "string"
          },
          "ZDXG_M100AK": {
            "type": "string"
          },
          "ZDXG_BSPER": {
            "type": "string"
          },
          "ZDXG_M55PA_FREI": {
            "type": "string"
          },
          "ZDXG_M65VF_FREI": {
            "type": "string"
          },
          "ZDXG_M80LF_FREI": {
            "type": "string"
          },
          "ZDXG_DATA_ORIGIN": {
            "type": "string"
          },
          "ZDXG_TIEFG": {
            "type": "string"
          },
          "ZDXG_MALLDQ": {
            "type": "string"
          },
          "ZDXG_BWARN": {
            "type": "string"
          },
          "ZDXG_PRAUSG": {
            "type": "string"
          },
          "ZDXG_DIV02L": {
            "type": "string"
          }
        },
        "required": [
          "VTWEG",
          "SKTOF",
          "VMSTA",
          "VMSTD",
          "ZDXG_VGBK",
          "ZDXG_VFGRP",
          "ZDXG_LKZ01",
          "ZDXG_LKZ19",
          "ZDXG_PRKLA",
          "ZDXG_EGHID",
          "ZDXG_PRGRP_GG",
          "ZDXG_MALL",
          "ZDXG_RGGEW",
          "ZDXG_M50FI",
          "ZDXG_M55PA",
          "ZDXG_M65VF",
          "ZDXG_M80LF",
          "ZDXG_M90AE",
          "ZDXG_M91TS",
          "ZDXG_M99MH",
          "ZDXG_M100AK",
          "ZDXG_BSPER",
          "ZDXG_M55PA_FREI",
          "ZDXG_M65VF_FREI",
          "ZDXG_M80LF_FREI",
          "ZDXG_DATA_ORIGIN",
          "ZDXG_TIEFG",
          "ZDXG_MALLDQ",
          "ZDXG_BWARN",
          "ZDXG_PRAUSG",
          "ZDXG_DIV02L"
        ]
      }
    },
    "required": [
      "MATNR",
      "ZDXG_YYBCEZNDR",
      "ZDXG_YYBCEZNSO",
      "ZDXG_YYKURZANGA",
      "VKORG",
      "CH_CLUST_KOND",
      "CH_CLUST_MARD",
      "CH_CLUST_MEAN",
      "CH_CLUST_MARA",
      "CH_CLUST_MVKE"
    ]
  }

=== ksilin/pyschemer/tests/DataProductCDPricing.json
{
   "MATNR": "3VA61105KM310AA0",
   "ZDXG_YYBCEZNDR": "3VA6110-5KM31-0AA0",
   "ZDXG_YYBCEZNSO": "3VA61105KM310AA0",
   "ZDXG_YYKURZANGA": "K0Y",
   "VKORG": "RGSE",
   "CH_CLUST_KOND": {
      "ZLP0_1000": {
         "KSCHL": "ZLP0",
         "KOTABNR": "502",
         "VTWEG": "00",
         "#############": "Nur aktueller Preis",
         "DATBI": "99991231",
         "DATAB": "20240703",
         "KSTBM": "           1.000",
         "KBETR": "       10.00",
         "KONWA": "EUR",
         "KPEIN": "    1",
         "KMEIN": "ST",
         "ZDXG_DATA_ORIGIN": "R"
      },
      "ZLP0_RG": {
         "KSCHL": "ZLP0",
         "KOTABNR": "502",
         "VTWEG": "00",
         "#############": "Nur aktueller Preis",
         "DATBI": "99991231",
         "DATAB": "20240108",
         "KSTBM": "           1.000",
         "KBETR": "    24500.00",
         "KONWA": "SEK",
         "KPEIN": "    1",
         "KMEIN": "ST",
         "ZDXG_DATA_ORIGIN": "R"
      }
   },
   "CH_CLUST_MARD": {
      "N001": {
         "WERKS": "RGSE",
         "ZDXG_LIFNR": "AC008110",
         "ZDXG_LIFZ": " 33",
         "ZDXG_MINBM": "         1.000",
         "ZDXG_NORBM": "         0.000",
         "ZDXG_MAXBM": "         9.000",
         "ZDXG_STFBM": "         1.000",
         "ZDXG_VPART": "SZ",
         "ZDXG_VPMNO": "         1.000",
         "ZDXG_VPMGR": "         0.000",
         "ZDXG_VPMEH": "ST",
         "ZDXG_DATA_ORIGIN": "R",
         "LAND1": "DE",
         "ZDXG_VLIEF": "X",
         "ZDXG_GENFLAG": "X"
      },
      "N002": {
         "WERKS": "RGSE",
         "ZDXG_LIFNR": "AC008110",
         "ZDXG_LIFZ": " 44",
         "ZDXG_MINBM": "        10.000",
         "ZDXG_NORBM": "         0.000",
         "ZDXG_MAXBM": "         0.000",
         "ZDXG_STFBM": "         1.000",
         "ZDXG_VPART": "SZ",
         "ZDXG_VPMNO": "         1.000",
         "ZDXG_VPMGR": "         0.000",
         "ZDXG_VPMEH": "ST",
         "ZDXG_LIFZ_AA": "X",
         "ZDXG_DATA_ORIGIN": "R",
         "LAND1": "DE",
         "ZDXG_GENFLAG": "X"
      }
   },
   "CH_CLUST_MEAN": {
      "HE": {
         "EAN11": "4042948851418",
         "EANTP": "HE",
         "HPEAN": "X"
      },
      "UC": {
         "EAN11": "804766306914",
         "EANTP": "UC"
      }
   },
   "CH_CLUST_MARA": {
         "MTART": "FERT",
         "MBRSH": "M",
         "MATKL": "KHD",
         "MEINS": "ST",
         "BRGEW": "        20.000",
         "NTGEW": "        10.000",
         "GEWEI": "G",
         "SPART": "01",
         "EXTWG": "SIEP",
         "ZDXG_SORT_02": "PS50021",
         "ZDXG_SORT_04": "10.00%",
         "ZDXG_FDBGT": "00000000",
         "ZDXG_ABGEB": "SSI",
         "ZDXG_VERANTW": "1000",
         "ZDXG_VERTRIEB": "X",
         "ZDXG_YYLASTUPD": "00000000",
         "ZDXG_YYMASCH": "A",
         "ZDXG_DATA_ORIGIN": "R",
         "ZDXG_0007": "X",
         "ZDXG_YYBCNORM": "F",
         "ZDXG_SWPFV": "0",
         "ERSDA": "20151130",
         "LAEDA": "20240704",
         "ZDXS_MARA_EXT1": {
            "ZDXG_PRODIS": "1",
            "ZDXG_TECH_PRDGR": "3VA6",
            "ZDXG_MHAFR": "00",
            "LAENGE": "         0.000",
            "BREITE": "         0.000",
            "HOEHE": "         0.000",
            "ZDXG_SENDE_ORGID": "A1103478",
            "ZDXG_PRODV": "1000",
            "ZDXG_FUEHRSPR": "D",
            "ZDXG_FUEHRSPR_LAISO": "DE",
            "ZDXG_GG_FLAG": "I",
            "ZDXG_GG_HINW": "Weitere Infos siehe SIOS"
         }
   },
   "CH_CLUST_MVKE":
      {
          "VTWEG": "00",
          "SKTOF": "X",
          "VMSTA": "LF",
          "VMSTD": "20150316",
          "ZDXG_VGBK": "R711",
          "ZDXG_VFGRP": "5452",
          "ZDXG_LKZ01": "CC-IC10",
          "ZDXG_LKZ19": "EMS",
          "ZDXG_PRKLA": "D",
          "ZDXG_EGHID": "0",
          "ZDXG_PRGRP_GG": "41J",
          "ZDXG_MALL": "0",
          "ZDXG_RGGEW": "         0.000",
          "ZDXG_M50FI": "00000000",
          "ZDXG_M55PA": "20140430",
          "ZDXG_M65VF": "20141001",
          "ZDXG_M80LF": "20150316",
          "ZDXG_M90AE": "00000000",
          "ZDXG_M91TS": "00000000",
          "ZDXG_M99MH": "00000000",
          "ZDXG_M100AK": "00000000",
          "ZDXG_BSPER": "00000000",
          "ZDXG_M55PA_FREI": "X",
          "ZDXG_M65VF_FREI": "X",
          "ZDXG_M80LF_FREI": "X",
          "ZDXG_DATA_ORIGIN": "R",
          "ZDXG_TIEFG": "SSI0478110",
          "ZDXG_MALLDQ": "G",
          "ZDXG_BWARN": "00000000",
          "ZDXG_PRAUSG": "0",
          "ZDXG_DIV02L": "SI EP"
      }
}
